version: "3.3"
services:
  zoneminder:
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
      # Аргументы используются только при создании нового контейнера из Dockerfile. При запуске существующего изменить их нельзя.
        - TZ=Asia/Yekaterinburg
        - ZM_VERSION=1.36
    image: zoneminder
    container_name: zoneminder
    network_mode: host
    volumes:
      - datastorage1:/datastorage1/
      - datastorage2:/datastorage2/
      - datastorage3:/datastorage3/
      - datastorage4:/datastorage4/
      - images:/var/cache/zoneminder/images/
      - init:/init/
      - backup:/backup/
      - cron:/cron/
      - db:/var/lib/mysql/
      - logs:/var/log/zm/
      - www:/var/www/wall/
      - cert:/cert/
      - apache_logs:/var/log/apache2/
    environment:
      # Полная очистка базы
      - CLEAR_DB=false
      # Расписание создания резервных копий
      - SHEDULE=0 0 1 */1 *
      - MYSQL_PORT=3307
      # Порт, на котором планиеруется сервер на хосте
      - HTTPS_PORT=4430
      # Данные из файла .env Нужны для рестрима камер
      - OBSERVER1=${OBSERVER1}
      - OBSERVER_PASSWORD1=${OBSERVER_PASSWORD1}
      - OBSERVER2=${OBSERVER2}
      - OBSERVER_PASSWORD2=${OBSERVER_PASSWORD2}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://127.0.0.1:80 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 50
    restart: always

volumes:
   # Места хранения видео 
   datastorage1:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/datastorage1/"
   datastorage2:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/datastorage2/"
   datastorage3:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/datastorage3/"
   datastorage4:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/datastorage4/"
   images:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/images/"
   # Если база пуста, отсюда берётся бекап
   init:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/init/"
   # Место хранения бекапов
   backup:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/backup/"
   # Место хранения скрипта бекапов, полезно если нужно внести правки в скрипт
   cron:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/cron/"
   # База с настройками, выненсена, чтобы не очищалась при перезапуске контейнера
   db:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/db/"
   # Логи zm
   logs:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/logs/"
   # Папка с сайтом мониторинга
   www:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/www/"
   cert:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/cert/"
   apache_logs:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/zoneminder/data/apache_logs/"
        
        

